-- +goose Up

ALTER TABLE user_profiles
  ADD COLUMN IF NOT EXISTS headline TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS about TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS preferred_role TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS semester TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS availability TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS goals TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS github_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS telegram_username TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS portfolio_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS stacks TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS interests TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- +goose Down

ALTER TABLE user_profiles
  DROP COLUMN IF EXISTS updated_at,
  DROP COLUMN IF EXISTS interests,
  DROP COLUMN IF EXISTS stacks,
  DROP COLUMN IF EXISTS portfolio_url,
  DROP COLUMN IF EXISTS telegram_username,
  DROP COLUMN IF EXISTS github_url,
  DROP COLUMN IF EXISTS goals,
  DROP COLUMN IF EXISTS availability,
  DROP COLUMN IF EXISTS semester,
  DROP COLUMN IF EXISTS preferred_role,
  DROP COLUMN IF EXISTS about,
  DROP COLUMN IF EXISTS headline;
